👷 chore: try max 10 times to package

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -122,7 +122,20 @@ jobs:
         if: ${{ !matrix.n3ds }}
         run: |
           cd build
-          cpack .
+          success=0
+          max_tries=10
+          for i in $(seq $max_tries); do
+            cpack . && success=1
+            if test $success = 1; then
+              break
+            fi
+            echo "Package creation failed. Sleep 1 second and try again."
+            sleep 1
+          done
+          if test $success = 0; then
+            echo "Package creation failed after $max_tries attempts."
+            exit 1
+          fi
 
       - name: Install linuxdeploy
         if: ${{ matrix.linux }}
